import type { Habit } from '@/domain/types';

export type HabitTemplate = Pick<
  Habit,
  'name' | 'emoji' | 'color' | 'identity' | 'twoMinute' | 'full' | 'weeklyTarget' | 'timeWindow' | 'hard' | 'stackAfter' | 'reward'
>;

/** Quick starts, each with a two-minute version (Make it easy). */
export const HABIT_TEMPLATES: HabitTemplate[] = [
  {
    name: 'Gym',
    emoji: '💪',
    color: '#2DD4BF',
    identity: 'I am someone who takes care of my body',
    twoMinute: 'Put on my gym clothes',
    full: 'Train for 45 minutes',
    weeklyTarget: 3,
    timeWindow: 'morning',
    hard: true,
    stackAfter: 'I drink my morning water',
    reward: 'a protein smoothie',
  },
  {
    name: 'Football',
    emoji: '⚽',
    color: '#F5B544',
    identity: 'I am an active person who plays',
    twoMinute: 'Pack my football bag',
    full: 'Play a 60-minute game',
    weeklyTarget: 2,
    timeWindow: 'evening',
    hard: true,
    stackAfter: 'I close my laptop',
    reward: 'dinner with friends',
  },
  {
    name: 'Read',
    emoji: '📖',
    color: '#8B7CF6',
    identity: 'I am a reader',
    twoMinute: 'Read one page',
    full: 'Read 10 pages',
    weeklyTarget: 5,
    timeWindow: 'evening',
    hard: false,
    stackAfter: 'I brush my teeth at night',
    reward: 'a cup of tea',
  },
  {
    name: 'Meditate',
    emoji: '🧘',
    color: '#60A5FA',
    identity: 'I am calm and in control',
    twoMinute: 'Take ten slow breaths',
    full: 'Meditate for 10 minutes',
    weeklyTarget: 4,
    timeWindow: 'morning',
    hard: false,
    stackAfter: 'I make my bed',
    reward: 'my first coffee',
  },
  {
    name: 'Walk',
    emoji: '🚶',
    color: '#A3E635',
    identity: 'I am someone who moves every day',
    twoMinute: 'Walk to the end of the street',
    full: 'Walk for 30 minutes',
    weeklyTarget: 5,
    timeWindow: 'afternoon',
    hard: false,
    stackAfter: 'I finish lunch',
    reward: 'my favourite podcast',
  },
  {
    name: 'Journal',
    emoji: '✍️',
    color: '#F472B6',
    identity: 'I am someone who understands myself',
    twoMinute: 'Write one sentence about today',
    full: 'Write a full page',
    weeklyTarget: 5,
    timeWindow: 'evening',
    hard: false,
    stackAfter: 'I get into bed',
    reward: 'ten minutes of music',
  },
  {
    name: 'Save money',
    emoji: '💰',
    color: '#FB923C',
    identity: 'I am someone who builds wealth',
    twoMinute: 'Move ₹100 to savings',
    full: 'Move 20% of income to investments',
    weeklyTarget: 1,
    timeWindow: 'anytime',
    hard: false,
    stackAfter: 'I get paid',
    reward: 'watching the savings bar grow',
  },
];
