import type { Quote, QuoteTheme } from '@/domain/quotes';

/**
 * Nudge library. Original lines (attributed to the app) plus short public-domain classics.
 * Habit-science ideas are paraphrased in our own words; no book text is reproduced.
 */
const ORIGINAL = 'After She Left';

const raw: [QuoteTheme, string, string?][] = [
  // consistency
  ['consistency', 'Show up small today. Small is how big things start.'],
  ['consistency', 'The streak is not the goal. Becoming the person who keeps it is.'],
  ['consistency', 'Two minutes counts. Showing up is the habit.'],
  ['consistency', 'You do not rise to your goals; you fall to your systems. Build a good one today.'],
  ['consistency', 'A boring day of keeping promises beats an exciting day of breaking them.'],
  ['consistency', 'Repetition is how a choice becomes a character.'],
  ['consistency', 'Same time, same place, same small step. Let the routine carry you.'],
  ['consistency', 'Progress hides in the days that feel like nothing happened.'],
  ['consistency', 'Do it on the good days. Do a smaller version on the bad days. Just do it.'],
  ['consistency', 'Consistency is a quiet kind of courage.'],
  ['consistency', 'Your habits are compounding right now, in one direction or the other.'],
  ['consistency', 'One percent better is invisible today and undeniable in a year.'],
  ['consistency', 'Keep the chain unbroken, even if the link is tiny.'],
  ['consistency', 'Motivation comes and goes. Systems stay.'],
  ['consistency', 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', 'Will Durant'],
  // identity
  ['identity', 'Every rep is a vote for the person you are becoming.'],
  ['identity', 'Do not try to finish a goal. Try to become the kind of person who would.'],
  ['identity', 'Act like the person you want to be, one small action at a time.'],
  ['identity', 'You are not starting over. You are starting from experience.'],
  ['identity', 'Ask: what would a healthy, steady person do next? Then do that.'],
  ['identity', 'Your past self made the mistakes. Your present self makes the choice.'],
  ['identity', 'Prove to yourself, once more today, that you can trust you.'],
  ['identity', 'Identity is built from evidence. Give yourself some today.'],
  ['identity', 'The person you are becoming is built in moments nobody sees.'],
  ['identity', 'First say to yourself what you would be; and then do what you have to do.', 'Epictetus'],
  ['identity', 'Waste no more time arguing about what a good man should be. Be one.', 'Marcus Aurelius'],
  ['identity', 'You are allowed to become someone new.'],
  // start-small
  ['start-small', 'Make it so easy you cannot say no.'],
  ['start-small', 'Shoes on is a workout. Book open is reading. Start there.'],
  ['start-small', 'Lower the bar until stepping over it is easy. Then step.'],
  ['start-small', 'Start before you feel ready. Readiness shows up after the start.'],
  ['start-small', 'The first two minutes are the whole battle. Win those.'],
  ['start-small', 'Small enough to do today, meaningful enough to repeat tomorrow.'],
  ['start-small', 'A tiny habit done is worth more than a perfect plan postponed.'],
  ['start-small', 'Master showing up before you master the routine.'],
  ['start-small', 'Do less than you think you should, more often than you think you can.'],
  ['start-small', 'The journey of a thousand miles begins with a single step.', 'Lao Tzu'],
  ['start-small', 'Begin at once to live, and count each separate day as a separate life.', 'Seneca'],
  ['start-small', 'Just open the door. The rest of the room will follow.'],
  // never-miss-twice
  ['never-miss-twice', 'Missing once is an accident. Missing twice is the start of a new habit.'],
  ['never-miss-twice', 'Yesterday slipped. Today is the comeback. Keep it small and keep it.'],
  ['never-miss-twice', 'Bad days happen. Two bad days in a row is a choice you can still avoid.'],
  ['never-miss-twice', 'The fastest way back on track is the smallest possible step, today.'],
  ['never-miss-twice', 'Do not let one miss become a story about who you are.'],
  ['never-miss-twice', 'You are one action away from being back in rhythm.'],
  ['never-miss-twice', 'Fall seven times, stand up eight.', 'Japanese proverb'],
  ['never-miss-twice', 'Recover fast. That is what consistent people actually do.'],
  ['never-miss-twice', 'Forgive the miss. Refuse the second one.'],
  // discipline
  ['discipline', 'Discipline is remembering what you want most, not what you want now.'],
  ['discipline', 'Feelings are visitors. Let them come; do the plan anyway.'],
  ['discipline', 'When it is hard, do the two-minute version. Never zero.'],
  ['discipline', 'No man is free who is not master of himself.', 'Epictetus'],
  ['discipline', 'While we are postponing, life speeds by.', 'Seneca'],
  ['discipline', 'Well done is better than well said.', 'Benjamin Franklin'],
  ['discipline', 'Lost time is never found again.', 'Benjamin Franklin'],
  ['discipline', 'You do not have to feel like it. You only have to start.'],
  ['discipline', 'Make the right thing the easy thing, and the wrong thing a little harder.'],
  ['discipline', 'Put the phone in another room. Put the shoes by the door. Design wins.'],
  ['discipline', 'The pause between the urge and the action is where you get stronger.'],
  ['discipline', 'Say no to the old pattern once more. It gets quieter every time.'],
  ['discipline', 'Your environment is a habit coach. Arrange it on purpose.'],
  // resilience
  ['resilience', 'You survived the hardest days. You can handle this one.'],
  ['resilience', 'Healing is not linear, but it is real.'],
  ['resilience', 'What broke you is also what taught you. Use the lesson.'],
  ['resilience', 'Pain is information, not instruction.'],
  ['resilience', 'Some days the win is simply not going back.'],
  ['resilience', 'Grow through what you go through.'],
  ['resilience', 'You are rebuilding, and rebuilding takes as long as it takes.'],
  ['resilience', 'A setback is a detour, not a dead end.'],
  ['resilience', 'You can miss someone and still choose yourself.'],
  ['resilience', 'The urge passes in minutes. The regret would stay for days. Wait it out.'],
  ['resilience', 'No man was ever wise by chance.', 'Seneca'],
  ['resilience', 'Calm is a skill. Breathe slowly and practice it now.'],
  ['resilience', 'Let the old chapter close. You are writing a better one.'],
  // purpose
  ['purpose', 'Remember why you started. Then take one step toward it.'],
  ['purpose', 'Live today like the person who already reached the goal.'],
  ['purpose', 'Your goal is a direction. Today is a step. Both matter.'],
  ['purpose', 'The life you want is built from days like this one.'],
  ['purpose', 'Clarity beats intensity. Know the next step and take it.'],
  ['purpose', 'Every habit today is a brick in the house you are building.'],
  ['purpose', 'Where focus goes, energy flows. Guard your attention.'],
  ['purpose', 'You have a right to your actions, but never to the fruits of your actions.', 'Bhagavad Gita 2.47'],
  [
    'purpose',
    'If one advances confidently in the direction of his dreams, he will meet with a success unexpected in common hours.',
    'Henry David Thoreau',
  ],
  ['purpose', 'Wealth consists not in having great possessions, but in having few wants.', 'Epictetus'],
  ['purpose', 'Make today a day your future self will thank you for.'],
  ['purpose', 'The goal is far. The next step is near. Look near.'],
  ['purpose', 'Purpose makes the hard parts worth it.'],
  // reward
  ['reward', 'Finish the habit, then enjoy the reward. Let your brain connect the two.'],
  ['reward', 'Celebrate the tiny win. Satisfaction is what makes habits stick.'],
  ['reward', 'Mark it done and feel it. That check is proof.'],
  ['reward', 'Watch the ring close today. You earned that feeling.'],
  ['reward', 'Treat yourself after, not instead.'],
  ['reward', 'Progress you can see is progress you will repeat.'],
  ['reward', 'Pair the hard thing with something you love.'],
  ['reward', 'Every completed day is a small trophy. Collect them.'],
  ['reward', 'Enjoy the process. The results are already on their way.'],
  ['reward', 'Be proud of the small things. They add up to the big ones.'],
  ['reward', 'You kept a promise to yourself. That is worth smiling about.'],
];

export const QUOTES: Quote[] = raw.map(([theme, text, author], i) => ({
  id: `q${String(i + 1).padStart(3, '0')}`,
  theme,
  text,
  author: author ?? ORIGINAL,
}));
